title: Ray Altenberg
description: Software Engineer
site_title: 'Ray Altenberg'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: missingno01
blog_url: https://www.rayaltenberg.com
email: rayaltenberg@gmail.com
keybase_username: missingno01
twitter_username: missingno01
reddit_username: missingno01

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics: 